import type { CardTemplate } from "../types/trivia";

export const CARD_TEMPLATES: CardTemplate[] = [
  {
    id: "geo-capital",
    name: "Country → Capital",
    description: "Name the capital for each country.",
    promptLabel: "Country",
    answerLabel: "Capital",
    tags: "geography",
    promptPlaceholder: "France",
    answerPlaceholder: "Paris",
  },
  {
    id: "book-author",
    name: "Book → Author",
    description: "Match books to their writers.",
    promptLabel: "Book",
    answerLabel: "Author",
    tags: "literature",
    promptPlaceholder: "1984",
    answerPlaceholder: "George Orwell",
  },
  {
    id: "term-def",
    name: "Term → Definition",
    description: "Recall definitions or short explanations.",
    promptLabel: "Term",
    answerLabel: "Definition",
    tags: "vocabulary",
    promptPlaceholder: "Photosynthesis",
    answerPlaceholder: "Plants convert light to chemical energy…",
  },
  {
    id: "qa",
    name: "Question → Answer",
    description: "General trivia Q&A style labels.",
    promptLabel: "Question",
    answerLabel: "Answer",
    tags: "trivia",
    promptPlaceholder: "Largest planet in our solar system?",
    answerPlaceholder: "Jupiter",
  },
  {
    id: "lang-pair",
    name: "Word → Translation",
    description: "Language study: cue in one language, answer in another.",
    promptLabel: "English",
    answerLabel: "French",
    tags: "language,french",
    promptPlaceholder: "Hello",
    answerPlaceholder: "Bonjour",
  },
  {
    id: "year-event",
    name: "Year → Event",
    description: "What happened in a given year?",
    promptLabel: "Year",
    answerLabel: "Event",
    tags: "history",
    promptPlaceholder: "1969",
    answerPlaceholder: "Moon landing",
  },
];
